language: node_js
node_js:
  - "10"
sudo: false
 
branches:
  only:
  - master
 
cache:
  directories:
    - node_modules
 
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key: 4d0f2754-3a8f-4960-bbcf-492fbd4a8905
  app: parcel-tracking-system-be
