language: node_js
node_js:
  - 10.13.0
install:
  - npm install
branches:
  only:
    - master
deploy: 
  provider: heroku
  api_key:
    secure: 4d0f2754-3a8f-4960-bbcf-492fbd4a8905
  app:
    master: parcel-tracking-system-be